version: '3.9'
services: 
  db:
    image: postgress:15
    container_name: postgressDB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: bdusuarios
    
